### ISSUE TITLE
Move to elastic.elasticsearch

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/infrastructure#117]
azavea.elasticsearch hasn't been updated for 4 years, and defaults to a version of elasticsearch that's 4 years out of date, and requires a java version that can't be installed on ubuntu16.04 (without downgrading things, which the role doesn't handle).

Switching to elastic.elasticsearch will require some work to come up with a new config that mirrors whatever azavea.elasticsearch was doing for us

**Comment by mlandauer** [comment]
For TVFY and PlanningAlerts we're using a non-local elasticsearch cluster kindly donated to us by elastic. So, not relevant anymore
