### ISSUE TITLE
Outbound mail from RTK is being rejected by some MXes

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/infrastructure#123]
Sounds similar to #122. We've had a report from a RTK user:

> I'm no longer getting email alerts from RightToKnow.
> 
> I checked my email server logs, and I can see righttoknow.org.au connecting, sending an EHLO, and then immediately sending a QUIT.

We don't (currently) send mail out from RTK using cuttlefish, and probably won't want to change that as RTK does its own mail handling. We do probably need to apply a similar fix to set the outbound hostname.

Update:

> I found the problem! My server is configured to require TLS so mail comms is protected with encryption. It looks like the RTK server doesn't support STARTTLS. :(

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_m9il)

**Comment by jamezpolley** [comment]
Also, our SPF records for righttoknow.org.au only list Google's records, which is going to make any mail going out direct from the RTK server seem suspicious.

**Comment by benrfairless** [comment]
Looks like Amazon have reported the IP range as being dynamic to Trend Micro (and possibly others): https://app.frontapp.com/open/cnv_1esdvvh

We probably need to figure out what’s needed for a static IP.

**Comment by jamezpolley** [comment]
I've created #132 to track the static IP issue.

**Comment by jamezpolley** [comment]
SPF records seem to be fine. We do have an `a` specifier, which means to allow mail from the `a` record corresponding to `righttoknow.org.au`, which resolves to the IP the mail is going out from. 

So I don't think there's anything more to do here.
