### ISSUE TITLE
Subscriptions for Vaultpress/Jetpack have expired

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/infrastructure#138]
If we're still wanting to use this we need to give new card details; if we aren't still wanting to use this we should turn it off.

I'm guessing that what's happened is that Automattic needs new card details

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_14i11)

**Comment by jamezpolley** [comment]
Vaultpress is included in Jetpack. I've re-activated Jetpack Premium - $143.55 for a year.

**Comment by katska** [comment]
oh hey @jamezpolley can you tell me where this is being used? We were just charged for it again.

**Comment by jamezpolley** [comment]
It's being used on oaf.org.au

Original reason for it seems to have been anti-spam features (https://oaf.slack.com/archives/C0299VB5S/p1533109516000122)

According to the notes above I decided to keep it because of Vaultpress - daily offsite backups

> VaultPress currently has 741 snapshots of your site dating back to 11:00pm, Thu, August 2, 2018. These are totals from your most recent snapshot.

I'm going to close this again as the original issue (subscription expiring in 2019) has long been resolved
