### ISSUE TITLE
AWS asking us to restrict public access to S3 buckets

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/infrastructure#140]
See linked message in Front for details of buckets

>We’re writing to notify you that your AWS account ..... has one or more S3 buckets that allow read or write access from any user on the Internet. By default, S3 buckets allow only the account owner to access the contents of a bucket; however, customers can configure S3 buckets to permit public access.
> 
> Unless you have a specific reason (such as hosting a public website) for this configuration, we recommend that you update your bucket and restrict public access. Your list of buckets configured to allow access by anyone on the Internet as of August 9, 2019 are:

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_19ayt)

**Comment by jamezpolley** [comment]
@mlandauer Is this something we should leave open?

**Comment by mlandauer** [comment]
Looking through the list of buckets which are publicly accessible they all look like they are ones that should be public. So, I'm going to close this issue as we don't have to change anything
