### ISSUE TITLE
Certbot unable to renew certificates on Righttoknow

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/infrastructure#147]
In fixing #146 certbot was updated to use the Nginx method to update certs on RightToKnow. However, testing shows that this is not working. Nginx logs show the requests from the LetsEncrypt validation server being received by Nginx and redirected, then refused:
```access.log
18737:127.0.0.1 - - [30/Mar/2020:10:52:42 +1100] "GET /.well-known/acme-challenge/7FmPrjZrROeq3DVU5drvYQNOCN2jctWjAt6Xrn5_PH8 HTTP/1.1" 301 185 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
18744:127.0.0.1 - - [30/Mar/2020:10:52:43 +1100] "GET /.well-known/acme-challenge/7FmPrjZrROeq3DVU5drvYQNOCN2jctWjAt6Xrn5_PH8 HTTP/1.1" 502 173 "http://righttoknow.org.au/.well-known/acme-challenge/7FmPrjZrROeq3DVU5drvYQNOCN2jctWjAt6Xrn5_PH8" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```
```error.log
66:2020/03/30 10:52:43 [crit] 19038#19038: *1648464 connect() to unix:/tmp/passenger.FwL43Wg/agents.s/core failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: www.righttoknow.org.au, request: "GET /.well-known/acme-challenge/7FmPrjZrROeq3DVU5drvYQNOCN2jctWjAt6Xrn5_PH8 HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.FwL43Wg/agents.s/core:", host: "www.righttoknow.org.au", referrer: "http://righttoknow.org.au/.well-known/acme-challenge/7FmPrjZrROeq3DVU5drvYQNOCN2jctWjAt6Xrn5_PH8"
```

**Comment by jamezpolley** [comment]
Certbot works with nginx by creating a new vhost config which looks a bit like this:

```
server {
  listen 80
  .....
}
```

This fails on RTK as Nginx doesn't listen on port 80, varnish does. Varnish forwards the request to Nginx on :8000 which doesn't know how to handle the request.

Couple of possible ways to handle this:

 - There's a third-party certbot plugin which attempts to munge the varnish config to serve the challenge files; but the author notes that it's not well tested, makes many assumptions, and throws a bunch of warnings when the code is analysed. I'd prefer not to use this.
 - Certbot has pre/post hooks which could be used to shut down varnish before the renewal and restart it afterwards. I'd prefer to avoid this as it causes a small unnecessary outage at least once per day.
 - Certbot supports a `webroot` method, which writes files into a specified directory. We could use this in conjunction with a small tweak to Nginx config so that Nginx knows that requests for `.well-known` should be served from that directory.

I'm going to go ahead with the third option for now.

**Comment by mlandauer** [comment]
Looks to be happening again

**Comment by jamezpolley** [comment]
Tracking new issue in https://github.com/openaustralia/infrastructure/issues/152
