### ISSUE TITLE
Spec servers

### ISSUE THREAD

**Issue by henare** [openaustralia/infrastructure#2]
Work out what specs we need for each of these new servers:

### OpenAustralia.org.au

* RAM: 2 GB
* Disk: 80 GB

Latest gzipped MySQL backup: 269 MB * (30 days + 12 months + 52 weeks) = 25 GB

The running database is about 1.5 GB.

```
henare@kedumba:~$ du -sh /srv/www/www.openaustralia.org/
11G     /srv/www/www.openaustralia.org/
henare@kedumba:~$
```

That's just over 45 GB. Plus system and growth: **80 GB**

### OpenAustraliaFoundation.org.au

(what `jamison` already has)

* RAM: 1 GB
* Disk: 10 GB

### PlanningAlerts

* RAM: 3 GB
* Disk: 80 GB

#### Disk

```
henare@kedumba:~$ du -h /srv/www/www.planningalerts.org.au/
6.7G    /srv/www/www.planningalerts.org.au/
henare@kedumba:~$ du -h /var/lib/automysqlbackup/*/pa_prod
3.2G    /var/lib/automysqlbackup/daily/pa_prod
3.0G    /var/lib/automysqlbackup/monthly/pa_prod
15G     /var/lib/automysqlbackup/weekly/pa_prod
henare@kedumba:~$
```

Up to 30 files could normally be in `/var/lib/automysqlbackup/daily/pa_prod` so I think a truer number is 15GB for this directory too (latest backup is 508 MB gzipped * 30 = ~15GB). That also makes the monthly directory 6 GB on the current backup size.

Adding up all the sizes from MySQL `show table status;` shows the database uses around 3.5 GB.

That's about 45GB. Plus system and growth: **80GB**

### Election Leaflets

* RAM: 1 GB
* Disk: 20 GB

Based on the latest backup database size, 6.8 MB, total required for automysqlbackup is 658 MB.

```
henare@kedumba:~$ du -sh /srv/www/www.electionleaflets.org.au/
11G     /srv/www/www.electionleaflets.org.au/
henare@kedumba:~$ 
```

Plus system and given we're not planning to add much to this: 20 GB.

### Right To Know

* RAM: 3 GB
* Disk: 30 GB

```
henare@kedumba:~$ sudo du -sh /srv/www/www.righttoknow.org.au/
13G     /srv/www/www.righttoknow.org.au/
henare@kedumba:~$ 
```

```
postgres=# SELECT pg_size_pretty(pg_database_size('alaveteli_production'));
 pg_size_pretty
----------------
 101 MB
(1 row)

postgres=#
```

On the new server we'll also have autopostgresbackup so that'll take some space.

This could have quite a bit of growth soon. Let's say 30GB.

### They Vote For You

* RAM: 2 GB
* Disk: 10 GB

Latest gzipped MySQL backup 9.1 MB, automysqlbackup should need 855 MB.

```
henare@kedumba:~$ du -sh /srv/www/theyvoteforyou.org.au/
3.3G    /srv/www/theyvoteforyou.org.au/
henare@kedumba:~$
```

### morph.io

(existing Linode)

* RAM: 4 GB
* Disk: 95 GB (62 used)

### cuttlefish.oaf.org.au

(existing Linode)

* RAM: 2 GB
* Disk: 50 GB (7.5 used)

## Staging

As above, 1x server per application. The memory and disk could potentially be lower for these machines (especially disk).

* OpenAustralia.org.au
* OpenAustraliaFoundation.org.au
* PlanningAlerts
* Election Leaflets
* Right To Know
* They Vote For You
* morph.io
* cuttlefish.oaf.org.au

**Comment by henare** [comment]
Do we move our two Linodes back to Octopus?

**Comment by mlandauer** [comment]
@henare we should raise that idea with Andrew, for sure

**Comment by henare** [comment]
@mlandauer cool, I've added them to the list above.

**Comment by mlandauer** [comment]
@henare I failed to remember that it's handy having morph.io and cuttlefish.oaf.org.au in the US for latency reasons - we should still think about it I guess. Just requires a little more thought.

**Comment by henare** [comment]
>@andys: just wanting to know roughly ram and disk for each

**Comment by henare** [comment]
### PlanningAlerts memory requirements

Here's a snapshot of passenger processes from `passenger-memory-stats`, run at 15:30 on Wednesday 11 Feb 2015:

```
2914   113.9 MB  85.0 MB   Passenger RackApp: /srv/www/www.planningalerts.org.au/app/current
3724   116.4 MB  86.5 MB   Passenger RackApp: /srv/www/www.planningalerts.org.au/app/current
6687   113.6 MB  84.8 MB   Passenger RackApp: /srv/www/www.planningalerts.org.au/app/current
14205  113.5 MB  84.4 MB   Passenger RackApp: /srv/www/www.planningalerts.org.au/app/current
23223  113.2 MB  84.3 MB   Passenger RackApp: /srv/www/www.planningalerts.org.au/app/current
24909  114.8 MB  86.0 MB   Passenger RackApp: /srv/www/www.planningalerts.org.au/app/current
15492  139.8 MB  99.5 MB   Passenger RackApp: /srv/www/www.righttoknow.org.au/current
15557  123.0 MB  62.6 MB   Passenger RackApp: /srv/www/cuttlefish.openaustraliafoundation.org.au/current
16847  144.9 MB  109.0 MB  Passenger RackApp: /srv/www/theyvoteforyou.org.au/current
25162  108.5 MB  68.4 MB   Passenger RackApp: /srv/www/test.righttoknow.org.au/current
29038  101.7 MB  35.4 MB   Passenger AppPreloader: /srv/www/theyvoteforyou.org.au/current
29241  119.3 MB  48.7 MB   Passenger RackApp: /srv/www/theyvoteforyou.org.au/current
30952  104.5 MB  35.2 MB   Passenger AppPreloader: /srv/www/www.righttoknow.org.au/current
31200  104.4 MB  35.3 MB   Passenger RackApp: /srv/www/www.righttoknow.org.au/current
```

There's 5 PlanningAlerts processes using ~85 MB each: **425 MB**

There are 2 background workers and it seems reasonable to assume the same memory usage for them: **170 MB**

At the time there were also 10 Apache processes (admittedly shared by all our sites), using around 32 MB each: **320 MB**

That comes to **915 MB** for the application. It seems reasonable to double it to **2 GB** since this is under normal load.

Adding another **1 GB** for system services and other things not counted above, like the Sphinxsearch daemon, also seems reasonable.

This comes to a **total of 3 GB**.

**Comment by henare** [comment]
I've now roughly specced everything and put details in the issue description. What do you think @andys?

**Comment by henare** [comment]
Andy said this all looked OK so I'll close this for now.
