### ISSUE TITLE
Open-source server monitoring

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/infrastructure#22]
Chances are we're going to not be able to use newrelic for all our server monitoring because we'll have too many servers. So, we'll probably have to setup our own monitoring infrastructure. That will be fun.

**Comment by mlandauer** [comment]
Looking at newrelic I can't understand what our current subscription actually gives us. @henare I wonder if you can help illuminate the situation?

**Comment by henare** [comment]
AFAIK it's 2 servers but I'd recommend contacting them if you have questions. A search in email should find the last conversations I was having with our latest account manager. I've found them to be very helpful over the phone.

**Comment by mlandauer** [comment]
Looks like we can use new relic for most of what we need at the moment. So, closing this as a won't fix
