### ISSUE TITLE
Do we want to run ssh on non-standard port again by default?

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/infrastructure#5]
It's certainly not security - just might reduce noise of random people knocking loudly on our door

**Comment by henare** [comment]
[SSH is rate limited](https://github.com/openaustralia/infrastructure/blob/master/roles/base-server/tasks/main.yml#L8-L12), from the docs:

> ufw supports connection rate limiting, which is useful for protecting
> against brute-force login attacks. ufw will deny connections if an IP
> address has attempted to initiate 6 or more connections in the last
> 30 seconds. See  http://www.debian-administration.org/articles/187
> for details.

So I think that covers it nicely.

**Comment by mlandauer** [comment]
Sounds good to me
