### ISSUE TITLE
Alaveteli + Ansible + Vagrant = ERROR: Decryption failed

### ISSUE THREAD

**Issue by andreicristianpetcu** [openaustralia/infrastructure#7]
Hi, 

Ansible n00b here trying to setup nuvasuparati.info with your Ansible + Alaveteli config. Now I am setting up the dev environment and I have an error. I made [a clone](https://github.com/andreicristianpetcu/infrastructure/blob/master/Vagrantfile) and removed all non-foi stuff but I think I might be missing some local encrypted variables.

What am I doing wrong?

```sh
$ cat ~/.infrastructure_ansible_vault_pass.txt
secret
$ vagrant up righttoknow.org.au.dev
......
Cleaning up downloaded VirtualBox Guest Additions ISO...
==> righttoknow.org.au.dev: Checking for guest additions in VM...
==> righttoknow.org.au.dev: Checking for host entries
==> righttoknow.org.au.dev: adding to (/etc/hosts) : 192.168.10.10
righttoknow.org.au.dev  # VAGRANT: d92aac01fdc0306fab4d852efb4544a7
(righttoknow.org.au.dev) / ade91b15-c094-4d57-b495-c4cfc98c3a8b
[sudo] password for andrei:
==> righttoknow.org.au.dev: Setting hostname...
==> righttoknow.org.au.dev: Configuring and enabling network interfaces...
==> righttoknow.org.au.dev: Mounting shared folders...
    righttoknow.org.au.dev: /vagrant => ~/infrastructure
==> righttoknow.org.au.dev: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true
ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o
UserKnownHostsFile=/dev/null -o ControlMaster=auto -o
ControlPersist=60s' ansible-playbook
--private-key=~/infrastructure/.vagrant/machines/righttoknow.org.au.dev/virtualbox/private_key
--user=vagrant --connection=ssh --limit='righttoknow.org.au.dev'
--inventory-file=~/infrastructure/.vagrant/provisioners/ansible/inventory
--sudo -vv --skip-tags=dns site.yml
ERROR: Decryption failed
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Thank you for publishing your infrastructure!

**Comment by henare** [comment]
Hey @andreicristianpetcu, well done on finding this repo and great to hear you're getting some use out of it :chicken: 

>Create a file in your home directory .infrastructure_ansible_vault_pass.txt with the secret password used to encrypt the secret info in this repo

This secret is obviously unique to OAF. It's used to encrypt secret variables like the SSL private key. You can see which ones they are in https://github.com/openaustralia/infrastructure/blob/master/roles/righttoknow/vars/main.yml

You'll need to replace our encrypted variables files with yours: https://github.com/openaustralia/infrastructure/blob/master/roles/righttoknow/vars/encrypted.yml

All this uses [Ansible Vault](http://docs.ansible.com/ansible/playbooks_vault.html) to encrypt the secrets.

Hopefully that gives you enough to go on to work it out. When you do work it out, please post what you did back here so if someone else needs it they can do it too.

**Comment by andreicristianpetcu** [comment]
Thank you, @henare! I will look into that!

**Comment by andreicristianpetcu** [comment]
I think I got it! :D

You have LOTS of encrypted vars all over the place, and even if I made a `roles/righttoknow/vars/encrypted.yml` file with my own variables and my own `~/.infrastructure_ansible_vault_pass.txt`, Ansible tried to decrypt the rest of the variables with THE SAME password! The rest of the files were encrypted with your openaustralia password, not mine! Also there is another alaveteli related encrypted file in `encrypted_vars/righttoknow.yml`

Thank you for your help @henare! It was obvious! I'm such a n00b :D

**Comment by henare** [comment]
Not a n00b thing at all @andreicristianpetcu :smiley: Well done on working it out!

What site are you using this on?

Do you think this is something useful we could contribute back to the Alaveteli community?

**Comment by andreicristianpetcu** [comment]
I'm working on http://nuvasuparati.info (Alaveteli based). For now I am interested only in setting this up. If it will work I will be glad to help any other Alaveteli-based site use the same infrastructure. Also I want to contribute back since you guys probably saved me a lot of work :)

Do you think creating an ansible task/playbook that regenerates all the encrypted files and encrypts them would be useful? I was thinking that a new person can run that first and then `vagrant up` and all the encrypted files will be encrypted with the same secret? Generating of the cookie, db passwords etc is still a manual process. You don't need to do it since you already did it once but if we want others to reuse this project an automated first step would help a lot.

PS: I just finished reading [Ansible for DevOps](https://github.com/geerlingguy/ansible-for-devops) so I hope I manage to figure out most of the issues I encounter.

**Comment by henare** [comment]
>I'm working on http://nuvasuparati.info (Alaveteli based). For now I am interested only in setting this up. If it will work I will be glad to help any other Alaveteli-based site use the same infrastructure. Also I want to contribute back since you guys probably saved me a lot of work :)

Interesting!

>Do you think creating an ansible task/playbook that regenerates all the encrypted files and encrypts them would be useful? I was thinking that a new person can run that first and then vagrant up and all the encrypted files will be encrypted with the same secret? Generating of the cookie, db passwords etc is still a manual process. You don't need to do it since you already did it once but if we want others to reuse this project an automated first step would help a lot.

I'm not sure what the right way to make this generic would be. I guess the only way to find out is to try something :smile:
