### ISSUE TITLE
run-with-lockfile.sh is missing, what am I doing wrong?

### ISSUE THREAD

**Issue by andreicristianpetcu** [openaustralia/infrastructure#8]
Hi, 

For some reason [this task](https://github.com/andreicristianpetcu/infrastructure/blob/nvs/roles/righttoknow/tasks/main.yml#L42-L46) fails. I cloned commonlib and ansible passed but what is the correct way to do it? I disabled non-alaveteli sites so this might be the cause.

``` bash
#mkdir -p /srv/www/current/
#cd /srv/www/current/
#git clone https://github.com/mysociety/commonlib.git
```

I ran using [my fork](https://github.com/andreicristianpetcu/infrastructure) of infrastructure, the secret is.... well.... `secret` in ~/.infrastructure_ansible_vault_pass.txt :)

**Comment by andreicristianpetcu** [comment]
I made a small [hack](https://github.com/andreicristianpetcu/infrastructure/commit/704ea6b471ef2d3e6e2de7a1e4c4521b772e8954) in my fork. Not sure if this is the correct way.

**Comment by henare** [comment]
>I guess ansible is used only for provisioning, not for deployment.

[That's correct](https://github.com/openaustralia/infrastructure#right-to-know).

However I think you may have found an actual issue here. [This file](https://github.com/andreicristianpetcu/infrastructure/blob/nvs/roles/righttoknow/tasks/main.yml#L50) isn't going to exist until you deploy.

**Comment by andreicristianpetcu** [comment]
@henare I made a [pull request](https://github.com/openaustralia/infrastructure/pull/9) that adds the missing run-with-lockfile.sh file.
